apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ningx
  name: ningx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ningx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ningx
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: {}
status: {}
